### PR TITLE
Implement OrthoMADS

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Hi @fsobral, do you mind if I ask you a few MADS related questions? I've implemented OrthoMADS here and I'm having problems with the constraints. I forbid leaving the feasible set in the algorithm, but when the iterate reaches the frontier close to the solution, it can't leave that point.

Here's an example:
```
using NLPModels, DerivativeFreeSolvers

nlp = ADNLPModel(x -> x[1]^2 + x[2]^2, ones(2), c=x->[2x[1] + x[2] - 1], lcon=[0.0], ucon=[Inf])
output = orthomads(nlp, max_eval=-1, steptol=0.0)
```

So my questions:
- is this expected?
- should I change to a penalization approach?
- theoretically, it should leave that point, is it normal to take so much time?
- do you have a different implementation of OrthoMADS (without all the magic stuff, like in NOMAD) to try this?

Thanks in advance.

**Comment by fsobral** [comment]
Hi @abelsiqueira 

>     * is this expected?
As far as I remember, this behavior occurs when you use a fixed/finite set of search directions. That shouldn't happen if you use random orthogonal directions. I do not remember how Halton sequences work... are they supposed to generate a dense set?

> 
>     * should I change to a penalization approach?
Penalization will work in the same way in this case.

> 
>     * theoretically, it should leave that point, is it normal to take so much time?
> 
>     * do you have a different implementation of OrthoMADS (without all the magic stuff, like in NOMAD) to try this?

When I implemented OrthoMADS, I did not use Halton sequences... I remember to generate one random direction and then build an orthogonal matrix using Householder reflections, as suggested by Ana Friedlander in some paper. Anyway, any implementation should work for this easy problem, unless your set of directions is not changing. Are you sure that the generated set is dense?

**Comment by abelsiqueira** [comment]
The directions should generate a dense set, so I'm guessing I'm not implementing things correctly. I'll take a second look, and possibly change to Householder then. Thanks!

**Comment by abelsiqueira** [comment]
The algorithm was correctly implemented, but it looks like the radius went to zero too quickly and didn't have time to improve enough, even after changing to random directions.

I'm closing this in favor of #5 which uses random directions, and leaving the branch in case we want to come back to this in the future.

Thanks, @fsobral, for the help.

**Pull request closed without merging**
